version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        - HOST_URL=http://localhost:5000
    #environment:
    #  - HOST_URL=http://localhost:5000
    ports:
      - "80:80"

  server:
    build: server
    ports:
      - "5000:5000"
    links:
      - database
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://database:27017/solidop
      - HOST_URL=http://localhost
    depends_on:
      - database

  database:
    image: mongo:3.6.3
    ports:
      - "27017:27017"
